### ISSUE TITLE
IsRunning = False, even if the copying process has not yet been completed

### ISSUE THREAD

**Issue by JoE-Seeve** [tjscience/RoboSharp#120]
What is the meaning of the different flags for IsRunning, IsPaused and IsCancelled?

I have observed the following:
- IsRunning == True -> If the copy process is running
- IsRunning == True and IsPaused == True -> If the copy process isn't stopped and the process is paused
- IsRunning == False and IsCancelled == True -> If the copy process is running but a cancelation was requested
- IsRunning == False and IsCancelled == True -> If the process has completed but was cancelled

I would actually expect the following:
- IsRunning == True and IsCancelled == True -> If the copy process is running but a cancelation was requested
- IsRunning == False and IsCancelled == False -> If the process has completed but was cancelled

I only noticed this when I copied to a very slow USB stick and the message was constantly displayed that the copying process was no longer running, but after that there was no "OnCommandCompleted" signal for minutes. Could someone please explain to me how you can interpret the signals to clearly show the state of the copying process? Thanks in advance.

**Comment by JoE-Seeve** [comment]
After more time to test the RoboSharp signals, I believe that there is more of a bug here. I found the following problems:
- IsCancelled is set to TRUE when the copy function is started for the first time if the copy process is stopped. But there is no code in RoboCommand.cs that sets IsCancelled back to FALSE.
- At the moment there is no signal that indicates that the copy process is running or is being ended after a STOP command. IsRunning is set to FALSE if IsCancelled = TRUE. The copying process can still run. Since IsCancelled is never set to FALSE, this flag does not indicate when the copying process is ended.

It should work with the following adjustments (at least for me):
- IsCancelled is set to FALSE every time a copy process is started, indicating that the current or the last copy process has been canceled. Most users will not notice this behavior because they reinitialize the class for each copy process, just as it is described in the example (RoboCommand backup = new RoboCommand();).
- A new CancellationRequested signal indicates that a cancellation or stop has been requested. This flag is set to TRUE on STOP and back to FALSE on completion of the copy process (IsCancelled does not need to be changed so that existing apps should not have any problems).

**Comment by PCAssistSoftware** [comment]
Sorry for delay in responding, when I get a moment in the coming days I will look into what you are saying and comment further.  I use those flags in my apps and have never noticed them returning wrong values though, but will certainly investigate

**Comment by JoE-Seeve** [comment]
Thank you very much for your info. I would like to present my solution via a pull request, but I still need time to read the help and then be able to use it.

**Comment by PCAssistSoftware** [comment]
Quick initial comments:-

The value of IsCancelled is set to False by default when you create a new instance of RoboCommand, it is changed to True when a copy process is cancelled - which is correct.  You would then usually discard that instance of RoboCommand before starting another copy process and then the value of IsCancelled will be set back to False as intended.  Am I missing something here?

**Comment by JoE-Seeve** [comment]
@PCAssistSoftware Yes, that's absolutely right for IsCancelled. But which signal then indicates the end of the copying process? It cannot be IsRunning because it is already set to FALSE when the process is requested to stop. And IsCancelled remains TRUE until a new copy process is started. A long time can pass between STOP (= IsRunning = FALSE / IsConcelled = TRUE) and Process Completed. The signals still show the same after the Process Completed Event (= IsRunning = FALSE / IsConcelled = TRUE).

**Comment by PCAssistSoftware** [comment]
I use the RoboCopyExitStatus of Successful to determine if a job is done, basically checking if that is True and IsCancelled is False then job is done

**Comment by JoE-Seeve** [comment]
Yes you can produce an additional signal or flag for this. But I think the signals implemented in RoboSharp should indicate every state. But that would only be the case if IsRunning remains TRUE until the copying process is ended.

**Comment by PCAssistSoftware** [comment]
RoboCopyExitStatus **is already implemented** in RoboSharp and is part of RoboSharp.Results, so I am **not** producing an additional signal or flag, I am using it as designed to be used

![image](https://user-images.githubusercontent.com/10872799/146185514-fce82a5b-db1f-4108-bfe8-f8fd25de1fc0.png)

**Comment by JoE-Seeve** [comment]
Yes, I know, but I only have RESULTS when the process has ended. I also need the status when the process is still running but a STOP has been requested.

**Comment by PCAssistSoftware** [comment]
Not sure what we are doing differently, but if I start a job and then cancel it I can still get RESULTS to determine the relevant state at that point e.g. Success = False, Cancelled = True and Exit Code of "-1 - Results not valid as operation cancelled"

![image](https://user-images.githubusercontent.com/10872799/146186972-eeccd34e-2eea-44c6-86ec-39070f6a3ee7.png)

**Comment by JoE-Seeve** [comment]
I also didn't notice this problem straight away because I always performed the copy processes with fast drives or networks. The status display in my app also always looked right. Then I once copied movies (5 x 900 MByte) onto a USB stick, stopped before finishing and then saw that the IsRunning display was off but the copying process continued for two minutes. Although I had the message IsCancelled, I only recognized that the copy process was still running because the Completed event had not yet been triggered.

**Comment by PCAssistSoftware** [comment]
I don't know what to say then - the test I was doing at that point was with multiple 512mb testfiles, and I was copying to a USB drive, when I click Cancel in my app the copy stops immediately and the values showing in my form are correct.  I cannot replicate your issue so will have to wait and see if anyone else can.

**Comment by PCAssistSoftware** [comment]
@JoE-Seeve - this should be resolved by #133 - can you please check and confirm for us? thank you :)

**Comment by JoE-Seeve** [comment]
I have just checked the IsRunning, IsCancelled signals again and nothing has changed for me. IsRunning is set to FALSE when IsCancelled is set to TRUE. However, IsRunning does not indicate when the process has actually ended. If the copying process is slow, the process sometimes runs for minutes after you call Cancel. Is this behavior wanted that way? If so, everything works fine, but then no boolean value indicates the end of the copying process.

For me, the IsRunning signal would be easier to understand if it is set at start (is implemented like this) and when OnCommandCompleted is reset immediately before the triggering (it is not implemented that way). IsRunning thus indicates with TRUE when a copying process is started and when it is finished.

After what I was able to test quickly, when Cancel is called, the task is prompted to end and IsRunning is set to FALSE. However, the task is only terminated after the file has been copied and only then is the OnCommandCompleted event triggered. However, the end of the copying process is not the same as resetting IsRunning.

**Comment by JoE-Seeve** [comment]
After a small test and two changes in RoboCommand.cs, IsRunning is set to FALSE when the copying process is reported as finished (and not already with Cancel / Stop).

![grafik](https://user-images.githubusercontent.com/92209494/148495166-1c51bef1-447e-451b-aeb4-60019cb2f98e.png)

![grafik](https://user-images.githubusercontent.com/92209494/148495204-cedb2292-8aff-40fa-84d2-313fddd4b45b.png)

**Comment by RFBomb** [comment]
I can review this tomorrow. 

> If the copying process is slow, the process sometimes runs for minutes after you call Cancel.

that surprises me, since we are simply calling ‘process.kill’, which should kill it immediately. I’ll do some USB to USB tests to force it slow as possible and test. 

>  Is this behavior wanted that way? If so, everything works fine, but then no boolean value indicates the end of the copying process.

the intended function is to immediately kill the process, so if it’s workin as you describe it’s not working as intended. 

> For me, the IsRunning signal would be easier to understand if it is set at start (is implemented like this) and when OnCommandCompleted is reset immediately before the triggering (it is not implemented that way). IsRunning thus indicates with TRUE when a copying process is started and when it is finished.


completely agree, this is an easy fix to implement. Currently Stop() sets the value, if we simply remove the line from the stop method, it will solely rely on the event reaction. 

> However, the task is only terminated after the file has been copied and only then is the OnCommandCompleted event triggered.

Interesting find! I’ll test this aspect out tomorrow and accommodate this. If this is true (which I don’t really doubt), several changes are required.

**Comment by JoE-Seeve** [comment]
> Interesting find! I’ll test this aspect out tomorrow and accommodate this. If this is true (which I don’t really doubt), several changes are required.

I have to add a few things here. 
- Since I did not test it with the RoboSharpApp, I will do it again and check it too.
- Between the termination with Stop and the OnCommandCompleted event, there are no longer any events that indicate the progress of the files to be copied (so the task does not seem to be running any longer).
- Why is the task hard ended with "process.Kill" instead of with "tokenSource.Cancel" from outside the task (if tokensource is declared differently)?

**Comment by RFBomb** [comment]
> Why is the task hard ended with "process.Kill" instead of with "tokenSource.Cancel" from outside the task (if tokensource is declared differently)?

that’s where this actually gets interesting. Because I had the same question, and modified both to use the cancel token while creating RoboQueue. The task created in Start() is spawning a robocopy process, and basically just watching it. That process is a whole other processes disconnected from the task, so cancelling the task itself does absolutely nothing to stop the robocopy process, you merely stop waiting for it to exit. 

In this scenario, results builder fires, but robocopy is not complete, so it’s inaccurate. Furthermore, since robocopy is still running, the events are also still being triggered since they are never unsubscribed from the running process. 

The task has `process.waitforexit` in it, so killing the process kills robocopy, which in turn allows the task to complete. 

Since I had commited the test thinking it worked, additional testing proved what I explained above, and I had to revert  my commit and go back to the current method. 

What the cancellation token does do is prevent the robocopy process ever getting started if an error is detected in the code above the task factory. For example, if the source does not exist, that cancelled the token. Since token is cancelled before task ever starts, task never runs. But the changes I made here, the continuation task will now always run. 

I found that when the cancel token was used,it prevent both main task and its continuation. Simply report `Task.Status = Cancelled `, without any code within them being hit.

**Comment by JoE-Seeve** [comment]
> that’s where this actually gets interesting. Because I had the same question, and modified both to use the cancel token while creating RoboQueue. The task created in Start() is spawning a robocopy process, and basically just watching it. That process is a whole other processes disconnected from the task, so cancelling the task itself does absolutely nothing to stop the robocopy process, you merely stop waiting for it to exit.

Usually, and this is how it is described by Microsoft, the token.cancel should also be used in such situations. It triggers the TaskCancellationException within the task and then it can be decided within the task what happens after this exception, even if I do not have access to the function call (here RoboCopy).

**Comment by RFBomb** [comment]
While I don’t really disagree here, the end result is the same, so current method is simpler and less resource intensive. 

WaitForExit basically stops the task in its tracks until the process exits, no further evaluation is done within the task until that occurs, meaning it’s also not really using resources. 

To do what you suggest would involve inserting a loop into the task that monitors both the cancel token and the process status. Then, if cancel is true but process still running, kill the task. 

This can lead to unwanted behavior vs the current method:
- extra resource wasted due to constant evaluation in the loop
- increased complexity By introducing the loop, kill logic, and then still having to require the call to WaitForExit or another loop waiting for OnCommandComplete to set the value to false. 
- Either Thread.Sleep or Task.Delay would have to be used consistently within those loops to ensure it doesn’t tax the cpu by doing an endless zero-time consuming loop. This can introduce context switching, which will degrade performance.

**Comment by JoE-Seeve** [comment]
> To do what you suggest would involve inserting a loop into the task that monitors both the cancel token and the process status. Then, if cancel is true but process still running, kill the task.

No, You just have to wait for the TaskCancellationException, catch it and then process it. But that's how it works.

**Comment by RFBomb** [comment]
Additional unwanted behavior:

if what you say about robocopy finishing the current copy operation prior to finishing, that could lead to another large copy operation getting started while the task is sleeping within the loop.

**Comment by RFBomb** [comment]
> No, You just have to wait for the TaskCancellationException, catch it and then process it. But that's how it works.

that is still introducing complexity where none is needed. Plus, it would require restructuring since some cleanup is done after robocopy exits.  This includes building the results.

**Comment by JoE-Seeve** [comment]
OK

**Comment by RFBomb** [comment]
This should be resolved in my #137 PR

**Comment by JoE-Seeve** [comment]
I would like to test IsRunning, but during testing I had the following two problems:
- On my new computer with Visual Studio 2022 there is only .Net 4.51 (or higher). But then StartAsync is not available (although it would run). As already noticed by other users, "NET45" should be changed to "NET45_OR_GREATER" there.
- Then I tested the current DEV version on my old computer, but stopped further tests because this version of the RoboSharpApp crashed at the first event (OnCommandCompleted - even if the process just started) during a simple copy process.

**Comment by PCAssistSoftware** [comment]
> * On my new computer with Visual Studio 2022 there is only .Net 4.51 (or higher). But then StartAsync is not available (although it would run). As already noticed by other users, "NET45" should be changed to "NET45_OR_GREATER" there.

Yes as documented VS2022 dropped support for .NET 4.5 - but you can easily get round this so you can still use it, which is easier than having to have both VS2019 and VS2022 installed - this is what I do myself - see here - https://thomaslevesque.com/2021/11/12/building-a-project-that-target-net-45-in-visual-studio-2022/

> * Then I tested the current DEV version on my old computer, but stopped further tests because this version of the RoboSharpApp crashed at the first event (OnCommandCompleted - even if the process just started) during a simple copy process.

UPDATE: Just downloaded fresh version and tested - having exact same problem here - tagging @RFBomb for info

**Comment by RFBomb** [comment]
I think I found a bug last night with Dev that was causing the crash and
will submit a Pr to fix after testing this morning.

Basically, the Async task is producing Task<task> , causing continuation
task to run prior to robocopy finishing. I didn’t know about this odd
interaction, so adding Unwrap should resolve it.

**Comment by RFBomb** [comment]
I was running into the issue of starting too many commands with RoboQueue, which was hanging the TaskScheduler implementation since the tasks were running on threads that were being slept, meaning no more tasks could run on those threads. 

SO I had made the sleep and `Process.WaitForExit` asynchonrous.

Well, I found out that `Task.Factory.StartNew` doesn't natively handle Async Tasks, but `Task.Factory.Run` does.
`Task.Factory.Run` silently detects if you are producing `Task<Task>` and unwraps it automatically. `StartNew `is lower level, and you have to unwrap it yourself. I was unaware of this nuance when I made that change. 
After researching the issue, I found a MS article that explains the nuance of `Task.Factory.StartNew ( async() =>` creates a task that returns an async task, so the continuation task fires as soon as the inner async task has done the first 'await'. This caused RoboCommand.Stop() to be called, and reported results that weren't build yet, crashing everything.

I have added `.Unwrap()` to the end of the StartNew() task, which instead of returning Task<Task> will now simply return the inner task. Tested this morning and it works as it used to, but now doesn't block the entire thread since its waiting asynchronously.

**Comment by JoE-Seeve** [comment]
Thanks @PCAssistSoftware that solved my first problem. Then I wait with further tests until the second problem is solved.

**Comment by PCAssistSoftware** [comment]
@JoE-Seeve - fix pushed for second problem, so you can do your further testing when convenient

**Comment by JoE-Seeve** [comment]
I just did a copy test with RoboSharpApp using "dev 4c66620". The copying process was carried out correctly. The same copying process caused the program to crash when I pressed Cancel.

**Comment by PCAssistSoftware** [comment]
Cancelling job confirmed as problem - @RFBomb 

![image](https://user-images.githubusercontent.com/10872799/149668618-f9ff45d9-726b-4bac-9a25-dd8f687125a0.png)

**Comment by PCAssistSoftware** [comment]
Commenting out above console.writeline - (which I think just need checking for nul first) - causes exception in different location

![image](https://user-images.githubusercontent.com/10872799/149668724-74c91f45-61c4-442f-b07b-5f2468f6a7ff.png)

**Comment by RFBomb** [comment]
Race Conditions for the win!
Stop() was disposing of `process` before resultsBuilder had a chance to react. My Async methodology exposed this race condition, but I had suspected it was there previously with the old `WaitForExit` in RoboComand.Start().

**Comment by PCAssistSoftware** [comment]
> Race Conditions for the win! Stop() was disposing of `process` before resultsBuilder had a chance to react. My Async methodology exposed this race condition, but I had suspected it was there previously with the old `WaitForExit` in RoboComand.Start().

Good spot!

**Comment by RFBomb** [comment]
Yea, I think it was pure luck that it wasn't failing due to the race condition previously, because it originally disposed of the process right as ResultsBuilder would have been evaluating Process.ExitStatus.

**Comment by PCAssistSoftware** [comment]
@JoE-Seeve - this should now be resolved, so please test original issue when you have a moment and let us know - thanks

**Comment by JoE-Seeve** [comment]
OK, everything is working now. But my problem is not really solved. Now everything is terminated correctly with Cancel, but the copying process continues in the background. This means that the user does not know when he can remove the storage medium. If he does that when the program says the copying process is finished, then he has to reckon with defective files.

It looks the same to me as before, except that RoboSharp now reports with Cancel that everything is finished (even though it isn't).

**Comment by RFBomb** [comment]
My testing with the backup app doesn't show this occurring. 

You are correct that 'cancelled' is set immediately when the process is stopped, but robocopy is killed, and it seems to be exiting fine. 

Are you subscribed to the 'command completed' event? Is that firing? Is this reproduced in the backup app? 

Are you starting it twice? If you start it while it's already running, the process loses its referee and can no longer be stopped

**Comment by JoE-Seeve** [comment]
So I tested again with the RoboSharpApp and used the ProcessExplorer to help (because you can use "robo" to filter all processes that start with robo). I found the following during a slow copy test:
- The RoboSharp copying process can be ended with "Cancel" -> The signals (IsRunning, IsCancelled) are as expected (from the developer).
- The copying process with RoboCopy continues until the file to be copied is completed or RoboCopy can react to an event (even if RoboSharpApp is already closed).
- When the copy process is finished, RoboCopy will also be terminated (which is to be expected).

In the current version, neither the signals (IsRunning, IsCancelled) nor the OnCommandCompleted event indicate whether the copying process is finished. In the old version of RoboSharp (dev 1.2.5), the end of the copy process was not indicated by IsRunning, but the OnCommandCompleted event was raised when the copy process was really finished by RoboCopy.

**Comment by RFBomb** [comment]
> first half of your comment

Sounds like it's working properly. During process exit, everything is sent the kill command and gets disposed of. If your evaluating events at this point, it's always going to be unreliable in any program because the exit/cleanup/garbage collection process that occurs as windows are being closed. 

> In the current version, neither the signals (IsRunning, IsCancelled) nor the OnCommandCompleted event indicate whether the copying process is finished. 

Is running isn't set to false until process.exit occurs, per your request (that I agree with). 

IsCancelled is set immediately when the stop request is issued, because that's the only reliable way to do it. 

OnCommandCompleted should not be firing until the process has exited either by cancellation or naturally. (An exception prevents this firing). 



> In the old version of RoboSharp (dev 1.2.5), the end of the copy process was not indicated by IsRunning, but the OnCommandCompleted event was raised when the copy process was really finished by RoboCopy.

Clarify what you want? As your post does not make it clear. It sounds here like you want OnCommandCompleted to only fire when successfully exiting, not cancelled. Which doesn't make sense to me, as results are now available either way.

**Comment by JoE-Seeve** [comment]
The problem is that after RoboSharp finishes the copying process, the RoboCopy copying process keeps running until RoboCopy finishes it. RoboCopy will continue to run the copy process started by RoboSharp even after RoboSharp exits.

Figure 1 - Defined copy process:
![grafik](https://user-images.githubusercontent.com/92209494/150635810-6e7a528d-966e-4b76-a41f-7fa11840457e.png)

Figure 2 - Started copy process
![grafik](https://user-images.githubusercontent.com/92209494/150635836-35847cff-4d86-4269-9e9e-b6cecb331411.png)

Figure 3 - Cancelled copy process -> Copying continues
![grafik](https://user-images.githubusercontent.com/92209494/150635841-7e84a567-4f88-4216-8bfd-c1f6c1a8c2fa.png)

Figure 4 - RoboSharpApp closed -> The copying process started by RoboSharpApp is still running
![grafik](https://user-images.githubusercontent.com/92209494/150635853-055e29a0-ab5d-4556-a5b3-f135b9fec23d.png)

RoboSharp indicated that the copy process was complete, but RoboCopy is still copying. This means that RoboSharp does not indicate whether the copying process has really ended. RoboSharp only shows if the task used for copying has finished.

**Comment by RFBomb** [comment]
> RoboSharp indicated that the copy process was complete

How exactly did it indicate that? The cancel button here is not a reliable indicator, since it doesn't get unlocked until process exits. 

The indicator would be results populating into the job history window. 

Further, process.kill is being issued to the process. At that point it's on the process and windows to kill it. Same during disposal.

**Comment by RFBomb** [comment]
What happens if you update RoboCommand line 292 in stop method from 

`process.Kill();`

To 

`process.Kill(true);`

**Comment by JoE-Seeve** [comment]
> How exactly did it indicate that? The cancel button here is not a reliable indicator, since it doesn't get unlocked until process exits.

The corresponding OnCompleted event was triggered and the copy results are then displayed.

I will do more tests tomorrow.

**Comment by RFBomb** [comment]
I just tried replicating this in the backup app, and was unable to do so. I was using a 7GB file to test with, and killing it around the 30-40% mark. 

I killed it using Stop() request and leaving the app open, and by closing the application. Both in Debug Mode (visual studio attached) and after building in running in release mode, without VS.

Note: I am working off #145

**Comment by JoE-Seeve** [comment]
I haven't had time in the last two weeks and only now have time to test with the latest RoboSharp dev release. It looks like the signals are now set as I would expect (IsRunning = False after the copy process is finished).

One last question on this topic: why is the copy process task aborted by kill/abort? Wouldn't the task also be terminated normally if you simply sent Control + C to RoboCopy? Anyway, according to my tests, the copy result is the same (RoboSharp task kill or Control + C). The last file is not completely copied (but it looks completely copied).

**Comment by RFBomb** [comment]
> why is the copy process task aborted by kill/abort?

Stop() kills RoboCopy process. This triggers the process.Exited event. This then allows the backuptask to finish. 

We can't stop the task itself because it would just stop monitoring the robocopy process, which would still run. However the robocopy process is killed doesn't matter, the task sees it and processes accordingly.

**Comment by JoE-Seeve** [comment]
Yes, I know how RoboSharp works, but wouldn't it be easier to stop the RoboCopy process via Control + C? Control + C stops RoboCopy and thus also the end of the task is reached and then the monitoring of the task (or RoboCopy) also stops.

**Comment by PCAssistSoftware** [comment]
Surely Ctrl+C is a keyboard shortcut to stop something running in a command line, not something you would use from within .NET app, hence why it is using Stop()

**Comment by JoE-Seeve** [comment]
Yes, but Control + C is mentioned in the Microsoft documentation for exactly that (in case you want to stop a program in the console before finishing work and a stop command isn't available). RoboSharp actually does the same thing a bit more complicated just by hard ending the task since the started process allows sending Control +C.

**Comment by PCAssistSoftware** [comment]
In all my years I have never come across anyone sending a keyboard command such as Control + C from within a .NET app when there are much better internal ways to do it.  

The way @RFBomb has done it works fine, so as far as I (and I suspect he) is concerned - case closed.

**Comment by JoE-Seeve** [comment]
... khank you for the statement.

**Comment by RFBomb** [comment]
> While in a command line such as MS-DOS, Linux, and Unix, Ctrl + C is used to send a SIGINT signal, which cancels or terminates the currently-running program

Aka process.kill()
